# Generated by Django 4.2.6 on 2023-11-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_rename_iscompleted_todo_isdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='1111-01-01'),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_Descr',
            field=models.CharField(default='Default Decr', max_length=150),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_List',
            field=models.CharField(default='Default List', max_length=10),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_Progress',
            field=models.CharField(default='Incomplete', max_length=15),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_Text',
            field=models.CharField(max_length=50),
        ),
    ]
