# Generated by Django 4.2.6 on 2023-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_todo_due_date_todo_task_descr_todo_task_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='0000-00-00'),
        ),
    ]
