# Generated by Django 4.2.6 on 2023-11-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_in_recycle_bin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_List',
            field=models.CharField(default='List', max_length=10),
        ),
        migrations.CreateModel(
            name='ModificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_fields', models.JSONField()),
                ('modification_date', models.DateTimeField(auto_now_add=True)),
                ('original_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.todo')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_date', models.DateTimeField(auto_now_add=True)),
                ('original_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.todo')),
            ],
        ),
    ]
