# Generated by Django 4.2.6 on 2023-11-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_todo_is_in_recycle_bin_alter_todo_task_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedtask',
            name='original_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='playground.todo'),
        ),
    ]
