# Generated by Django 4.2.6 on 2023-11-14 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0010_alter_deletedtask_original_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletedtask',
            name='id',
        ),
        migrations.AlterField(
            model_name='deletedtask',
            name='original_task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='playground.todo'),
        ),
    ]
