# Generated by Django 4.2.6 on 2023-11-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0011_remove_deletedtask_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('ListName', models.CharField(default='Personal', max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_Descr',
            field=models.CharField(default='Default Decription', max_length=150),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.list'),
        ),
    ]
